user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#REST
rest :
  type : rest
  resource : "routing_rest.yml"
  prefix : /api